language: php
dist: xenial
php:
    - '7.2'
node_js:
    - '9.4'
before_script:
    - cd src/php
    - composer install
    - npm install
    - npm run build
    - cd ../src/js
    - npm install
script:
    - cd src/php
    - vendor/bin/phpstan analyse Chaplin
    - vendor/bin/phpcs --standard=PSR2 Chaplin
    - node_modules/.bin/eslint
    - cd ../src/js
    - node_modules/.bin/eslint
