language: php
dist: xenial
php:
    - '7.2'
before_script:
    - cd src/php
    - composer install
script:
    - vendor/bin/phpunit --bootstrap ../../test/php/bootstrap.php -c ../../test/php/phpunit.xml
    - vendor/bin/phpstan analyse Chaplin
    - vendor/bin/phpcs --standard=PSR2 Chaplin
