language: php
dist: xenial
php:
    - '7.2'
before_script:
    - cd src/php
    - composer install
script:
    - cd src/php
    - vendor/bin/phpstan analyse Chaplin
    - vendor/bin/phpcs --standard=PSR2 Chaplin
